# Generated by Django 3.1.4 on 2020-12-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('countryImage', models.ImageField(default='default.jpg', upload_to='countryImage/')),
                ('nativeName', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('countryCode', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
