# Generated by Django 3.1.4 on 2020-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('country_image', models.ImageField(default='default.jpg', upload_to='country_image/')),
                ('native_name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('laguage', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
