# Generated by Django 3.1.4 on 2020-12-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='country',
            name='countryImage',
            field=models.ImageField(default='default.jpg', upload_to='countryImage/'),
        ),
    ]
